import fs from 'fs';
import path from 'path';
import { decodeHTML, fetchHtml } from './scraper_utils.js';
import * as cheerio from 'cheerio';
import { fileURLToPath } from 'url';
const __dirname = path.dirname(fileURLToPath(import.meta.url));

const BASE_URL = 'https://bridgetownbites.com/2026/07/20/2026-portland-salad-week-restaurant-specials-oregon/';

function parseSalads(html) {
  const $ = cheerio.load(html);
  const items = [];

  $('h2.wp-block-heading').each((i, el) => {
    const rawTitle = $(el).text().trim();
    if (!rawTitle || !rawTitle.includes(':')) return;

    const [restaurantRaw, dishRaw] = rawTitle.split(':').map(s => s.trim());
    
    let description = '';
    let address = '';
    let price = '';
    let hours = '';

    let next = $(el).next();
    while (next.length && next[0].name !== 'h2') {
      const text = next.text().trim();
      const htmlContent = next.html() || '';
      
      // Heuristic for address: looks for "Portland" or state/zip code
      if (text.includes('Portland') && (htmlContent.includes('<em>') || text.match(/NW|SW|NE|SE|Ste|Suite/i))) {
        address = text;
      } else if (text.length > 20) {
        // Assume it's the description if it's a long paragraph and not the address block
        if (!description) description = text;
        else description += '\n\n' + text;
      }
      
      next = next.next();
    }

    const overrides = {
      'Cibo': '3539 SE Division St, Portland, OR 97202',
      'Crisp Salads': '3901 N Williams Ave, Portland, OR 97227', // Only using one location for simplicity
      'Harlow': '3715 SE Division St, Portland, OR 97202',      // Only using one location
      'Spoons PDX': '1734 NW Northrup St, Portland, OR 97209',  // Looked up online
      'Bethany’s Table': '15325 NW Central Dr, Portland, OR 97229', // Removed Suite
      'Kachka Fabrika': '2117 NE Oregon St, Portland, OR 97232',    // Removed Suite
      'Nostrana': '1401 SE Morrison St, Portland, OR 97214'         // Removed Suite
    };

    // Clean address (remove website link text, etc.)
    if (address) {
      // It usually looks like "15325 NW Central Drive, Portland. Bethany's Table website"
      const parts = address.split('. ');
      address = parts.length > 1 ? parts[0] : address;
      address = address.replace(/[\n\r]+/g, ' ').trim();
    }
    
    const restaurantName = decodeHTML(restaurantRaw);
    if (overrides[restaurantName]) {
      address = overrides[restaurantName];
    }

    // Extract price from description
    const priceMatch = description.match(/\$(\d+)/);
    if (priceMatch) {
      price = priceMatch[0];
    }

    const id = Date.now() + Math.floor(Math.random() * 100000);
    items.push({
      id: id,
      weekId: 'salad-2026',
      isNew: true,
      restaurant: decodeHTML(restaurantRaw),
      dish: decodeHTML(dishRaw),
      desc: decodeHTML(description),
      address: decodeHTML(address),
      price: price,
      hours: hours,
      vegan: false,
      vegetarian: false,
      gf: false,
      dietary: { vegan: false, vegetarian: false, gf: false } // Disabled for now per user instruction
    });
  });

  return items;
}

const GEO_DELAY = 1100;
const GEO_UA = 'pdx-food-week-app/1.0 (https://github.com/oberonix/pdx-food-week)';
const sleep = ms => new Promise(r => setTimeout(r, ms));

async function geocode(address) {
  if (!address) return null;
  const q = encodeURIComponent(address);
  const url = `https://nominatim.openstreetmap.org/search?q=${q}&format=json&limit=1&countrycodes=us`;
  const res = await fetch(url, { headers: { 'User-Agent': GEO_UA } });
  if (!res.ok) return null;
  const data = await res.json();
  if (data && data[0]) {
    return { lat: parseFloat(data[0].lat), lng: parseFloat(data[0].lon) };
  }
  return null;
}

async function main() {
  console.log(`Fetching ${BASE_URL}...`);
  let html = '';
  try {
     html = await fetchHtml(BASE_URL);
  } catch (e) {
     console.error('Failed to fetch:', e);
     return;
  }

  const items = parseSalads(html);
  console.log(`Found ${items.length} salads. Geocoding...`);
  
  for (const item of items) {
    if (item.address) {
      await sleep(GEO_DELAY);
      const coords = await geocode(item.address);
      if (coords) {
        item.lat = coords.lat;
        item.lng = coords.lng;
        console.log(`  [Geocoded] ${item.restaurant} (${item.lat}, ${item.lng})`);
      } else {
        console.warn(`  [Miss] ${item.restaurant} - ${item.address}`);
      }
    }
  }

  const outPath = path.join(__dirname, 'data', 'salads2026.js');
  let code = `// Auto-generated by scrape_salads.js\n`;
  code += `window.FOOD_WEEKS = window.FOOD_WEEKS || [];\n`;
  code += `window.FOOD_WEEKS.push({\n`;
  code += `  id: "salad-2026",\n`;
  code += `  name: "Portland Salad Week 2026",\n`;
  code += `  organizer: "Bridgetown Bites",\n`;
  code += `  startDate: "2026-07-22",\n`;
  code += `  dates: "July 22 - 31, 2026",\n`;
  code += `  pricePills: ["$15-$29"],\n`;
  code += `  color: "#4CAF50",\n`;
  code += `  emoji: "🥗",\n`;
  code += `  totalLocations: ${items.length},\n`;
  code += `  url: "https://bridgetownbites.com/2026/07/20/2026-portland-salad-week-restaurant-specials-oregon/",\n`;
  code += `});\n`;
  code += `window.RESTAURANTS = window.RESTAURANTS || [];\n`;
  code += `(function() {\n`;
  code += `  const newItems = ${JSON.stringify(items, null, 2)};\n`;
  code += `  newItems.forEach(i => window.RESTAURANTS.push(i));\n`;
  code += `})();\n`;
  fs.writeFileSync(outPath, code);
  console.log(`\nWrote ${items.length} items to ${outPath}`);
}

main().catch(console.error);
